### ISSUE TITLE
Prepare training corpus

### ISSUE THREAD

**Issue by aashnakanuga** [lit-mod-viz/algo-detection#4]
Prepare a training corpus with the end goal of a .txt or .csv dataset containing one sentence / snippet per line.

**Comment by denten** [comment]
I think we should also add Plotto and Polti as the "data type" is very similar (short, sentences). I included the full list in the readme and uploaded the pdfs to the shared drive. We can skip digitizing the Comedy volume, I think. The next step would be a. to OCR the pdfs and b. to clean up the data by hand, cutting out the part that are not necessary.
